version: "3.0"
services:
  ping-service:
    build: ping
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 3s
  receiver-service:
    build: receiver
    hostname: ReceiverService
    ports:
      - "8081:8080"

